package com.veer.maya;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.util.*;
public class MainActivity extends Activity{EditText key,chat;TextView log;BroadcastReceiver rr;
TextView tv(String s){TextView v=new TextView(this);v.setText(s);v.setTextSize(16);v.setPadding(18,14,18,14);return v;}
@Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(24,24,24,24);TextView title=tv("MAYA — JARVIS Android Assistant");title.setTextSize(24);l.addView(title);l.addView(tv("AI • Voice • Memory • Phone Control"));
key=new EditText(this);key.setHint("OpenAI API key (sk-...)");key.setSingleLine(true);key.setInputType(129);l.addView(key);Button save=new Button(this);save.setText("SAVE API KEY");save.setOnClickListener(v->{MayaCore.saveKey(this,key.getText().toString());toast("API key saved");});l.addView(save);
Button acc=new Button(this);acc.setText("1. ACCESSIBILITY SETTINGS");acc.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));l.addView(acc);
Button mic=new Button(this);mic.setText("2. START MAYA VOICE");mic.setOnClickListener(v->{if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},20);else MayaVoiceService.start(this);});l.addView(mic);
chat=new EditText(this);chat.setHint("Type to MAYA…");l.addView(chat);Button ask=new Button(this);ask.setText("ASK MAYA");ask.setOnClickListener(v->{String x=chat.getText().toString().trim();if(!x.isEmpty()){MayaCore.process(this,x);chat.setText("");}});l.addView(ask);log=tv("MAYA ready.\n");l.addView(log,new LinearLayout.LayoutParams(-1,0,1));setContentView(l);
rr=new BroadcastReceiver(){public void onReceive(Context c,Intent i){if("com.veer.maya.REPLY".equals(i.getAction())){String x=i.getStringExtra("text");if(x!=null)log.append("\\nMAYA > "+x+"\\n");}}};registerReceiver(rr,new IntentFilter("com.veer.maya.REPLY"),RECEIVER_NOT_EXPORTED);}
void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}@Override protected void onDestroy(){try{unregisterReceiver(rr);}catch(Exception e){}super.onDestroy();}}
